### ISSUE TITLE
Elementos Aún pendientes para seleccionar y trabajar en ellos! 

### ISSUE THREAD

**Issue by Lostovayne** [Lostovayne/car-rent-website#5]
Agregaré una lista con imagen de los elementos que aún están pendiente para tomar

**Comment by Lostovayne** [comment]
1 - Imágenes de Vehiculos en webp
2 - Json de informacion para Vehiculos
3 - Barra de Filtrado de Vehiculos
4 - Seccion Reviews
5 - Slider de imagenes para vista de vehiculo
6 - Formulario de Pago

**Comment by Casadjes** [comment]
actualiza esa wea para no madrearte
